#tomcat config
server:
    port: 8081

spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/skills
        username: username
        password: password

    flyway:
        url: jdbc:postgresql://localhost:5432/skills
        user: username
        password: password
        baseline-on-migrate: true